implement checksum validation in wget
@nsheff I was able to implement the validation, but exiting in case of a mismatch does not work. It might be due to this running in a subshell or sth, I'm not sure. I decided to remove the downloaded file when a mismatch is detected.

diff --git a/pipeline_interfaces/wget_piface.yaml b/pipeline_interfaces/wget_piface.yaml
--- a/pipeline_interfaces/wget_piface.yaml
+++ b/pipeline_interfaces/wget_piface.yaml
@@ -6,8 +6,15 @@ command_template: >
       if [ -f "{sample.input_value[loop.index0]}" ]; then
         cp {sample.input_value[loop.index0]} {sample.local_input + sample.input_id[loop.index0]}
       else
-        { 'wget -nc -O ' + sample.local_input  + sample.input_id[loop.index0] + ' ' + sample.input_value[loop.index0] }; 
-      fi 
+        { 'wget -nc -O ' + sample.local_input + sample.input_id[loop.index0] + ' ' + sample.input_value[loop.index0] }; 
+      fi
+      checksum=`{'md5sum ' + sample.local_input + sample.input_id[loop.index0] + ' | cut -c -32'}`;
+      if [[ "{sample.checksum[loop.index0]}" != $checksum ]]; then
+        echo -e "\e[1;31mERROR: checksums don't match\e[0m: {sample.checksum[loop.index0]}, $checksum"
+        rm {sample.local_input + sample.input_id[loop.index0]}
+        exit 1
+      else
+        echo -e "checksums match: $checksum";
+      fi
     {% endif %}
   {%- endfor -%}
-  
